/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import ComponenteJCandado.JCandado;
import ComponenteJCandado.JCandadoEvent;
import ComponenteJCandado.JCandadoListener;
import javax.swing.DefaultListModel;

/**
 *
 * @author usuario
 */
public class JFrameTest extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTest
     */
    private DefaultListModel bloqueados= new DefaultListModel();
    private DefaultListModel seleccionados= new DefaultListModel();
    
    
    
    public JFrameTest() {
        initComponents();
        iniciaMisComponentes();
    }

    private void iniciaMisComponentes(){
        jListCandadosBloqueados.setModel(bloqueados);
        jListSeleccionados.setModel(seleccionados);
        
    }
    
    private class gestorCandados implements JCandadoListener{

        @Override
        public void bloqueado(JCandadoEvent evt) {
            bloqueados.addElement(evt.getSource());
            consistencia();
        }

        @Override
        public void seleccionado(JCandadoEvent evt) {
            seleccionados.addElement(evt.getSource());
            consistencia();
        }
        
    }
    
    private void consistencia(){
        jPanelCandados.repaint();
        jPanelCandados.revalidate();
        jButtonCierraTodos.setEnabled(seleccionados.size()>0);
        jButtonDesbloquear.setEnabled(jListCandadosBloqueados.getSelectedIndex()!=-1);
        jButtonCrearNuevosCandados.setEnabled("".equals(jTextFieldNumeroCandadosNuevos.getText()));
    }
    
    private gestorCandados gestCandados= new gestorCandados();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCandados = new javax.swing.JPanel();
        jPanelGestion = new javax.swing.JPanel();
        jLabelidCandado = new javax.swing.JLabel();
        jTextFieldIdNuevosCandados = new javax.swing.JTextField();
        jLabelNuevosCandados = new javax.swing.JLabel();
        jTextFieldNumeroCandadosNuevos = new javax.swing.JTextField();
        jButtonCrearNuevosCandados = new javax.swing.JButton();
        jLabelErrores = new javax.swing.JLabel();
        jPanelBloqueados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCandadosBloqueados = new javax.swing.JList<>();
        jButtonDesbloquear = new javax.swing.JButton();
        jPanelSeleccionados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSeleccionados = new javax.swing.JList<>();
        jButtonCierraTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCandados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Candados"));

        jPanelGestion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gestion"));

        jLabelidCandado.setText("Id nuevos candados");

        jTextFieldIdNuevosCandados.setText("jTextField1");

        jLabelNuevosCandados.setText("Nuevos candados");

        jTextFieldNumeroCandadosNuevos.setText("jTextField1");

        jButtonCrearNuevosCandados.setText("Crear nuevos candados");
        jButtonCrearNuevosCandados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearNuevosCandadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGestionLayout = new javax.swing.GroupLayout(jPanelGestion);
        jPanelGestion.setLayout(jPanelGestionLayout);
        jPanelGestionLayout.setHorizontalGroup(
            jPanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelErrores, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addGroup(jPanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldNumeroCandadosNuevos)
                        .addComponent(jLabelidCandado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNuevosCandados)
                        .addComponent(jButtonCrearNuevosCandados, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addComponent(jTextFieldIdNuevosCandados)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGestionLayout.setVerticalGroup(
            jPanelGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGestionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelidCandado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIdNuevosCandados, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrores, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNuevosCandados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumeroCandadosNuevos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCrearNuevosCandados)
                .addGap(13, 13, 13))
        );

        jPanelBloqueados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Candados Bloqueados"));

        jScrollPane1.setViewportView(jListCandadosBloqueados);

        jButtonDesbloquear.setText("Desbloquear Marcados");
        jButtonDesbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesbloquearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBloqueadosLayout = new javax.swing.GroupLayout(jPanelBloqueados);
        jPanelBloqueados.setLayout(jPanelBloqueadosLayout);
        jPanelBloqueadosLayout.setHorizontalGroup(
            jPanelBloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBloqueadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanelBloqueadosLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButtonDesbloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanelBloqueadosLayout.setVerticalGroup(
            jPanelBloqueadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBloqueadosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButtonDesbloquear)
                .addContainerGap())
        );

        jPanelSeleccionados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Candados Seleccionados"));

        jScrollPane2.setViewportView(jListSeleccionados);

        jButtonCierraTodos.setText("Cierra todos los de la lista");
        jButtonCierraTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCierraTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSeleccionadosLayout = new javax.swing.GroupLayout(jPanelSeleccionados);
        jPanelSeleccionados.setLayout(jPanelSeleccionadosLayout);
        jPanelSeleccionadosLayout.setHorizontalGroup(
            jPanelSeleccionadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanelSeleccionadosLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jButtonCierraTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSeleccionadosLayout.setVerticalGroup(
            jPanelSeleccionadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionadosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCierraTodos)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCandados, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCandados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBloqueados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSeleccionados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearNuevosCandadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearNuevosCandadosActionPerformed
        int numeroCandados;
//        try {
            numeroCandados=Integer.parseInt(jTextFieldNumeroCandadosNuevos.getText());
            for (int i = 0; i < numeroCandados ; i++) {
                JCandado candado= new JCandado(jTextFieldIdNuevosCandados.getText());
                candado.setListener(gestCandados);
                
                jPanelCandados.add(candado);
                consistencia();
                System.out.println("aññadido");
            }
//        } catch (Exception e) {
//            jLabelErrores.setText("Error numero de candados incorrecto");
//            System.out.println("error");
//        }
    }//GEN-LAST:event_jButtonCrearNuevosCandadosActionPerformed

    private void jButtonCierraTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCierraTodosActionPerformed
        for (int i = 0; i < seleccionados.size(); i++) {
            ((JCandado)seleccionados.get(i)).cerrar();
            seleccionados.remove(i);
        }
        consistencia();
    }//GEN-LAST:event_jButtonCierraTodosActionPerformed

    private void jButtonDesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesbloquearActionPerformed
        
        for (Object o : jListCandadosBloqueados.getSelectedValues()) {
            ((JCandado)o).desbloquear();
            bloqueados.removeElement(o);
        }
        consistencia();
    }//GEN-LAST:event_jButtonDesbloquearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCierraTodos;
    private javax.swing.JButton jButtonCrearNuevosCandados;
    private javax.swing.JButton jButtonDesbloquear;
    private javax.swing.JLabel jLabelErrores;
    private javax.swing.JLabel jLabelNuevosCandados;
    private javax.swing.JLabel jLabelidCandado;
    private javax.swing.JList<String> jListCandadosBloqueados;
    private javax.swing.JList<String> jListSeleccionados;
    private javax.swing.JPanel jPanelBloqueados;
    private javax.swing.JPanel jPanelCandados;
    private javax.swing.JPanel jPanelGestion;
    private javax.swing.JPanel jPanelSeleccionados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldIdNuevosCandados;
    private javax.swing.JTextField jTextFieldNumeroCandadosNuevos;
    // End of variables declaration//GEN-END:variables
}
