/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MisComponentes.ComponenteCuentaAtras;

import java.util.ArrayList;

/**
 *
 * @author usuario
 */
public class JCuentaAtras extends javax.swing.JPanel {

    private int valorInicio = 5;
    private int valorActual;

    public int getValorInicio() {
        return valorInicio;
    }

    public void setValorInicio(int valorInicio) {
        this.valorInicio = valorInicio;
        jLabelVisor.setText(String.valueOf(this.valorInicio));
        valorActual = valorInicio;
    }

    public int getValorActual() {
        return valorActual;
    }

    /**
     * Creates new form JCuentaAtras
     */
    public JCuentaAtras() {
        initComponents();
        setValorInicio(valorInicio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDetonador = new javax.swing.JButton();
        jLabelVisor = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jButtonDetonador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDetonador.setText("Detona en ...");
        jButtonDetonador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetonadorActionPerformed(evt);
            }
        });

        jLabelVisor.setBackground(new java.awt.Color(0, 0, 51));
        jLabelVisor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelVisor.setForeground(new java.awt.Color(0, 204, 51));
        jLabelVisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVisor.setText("99");
        jLabelVisor.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDetonador, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVisor, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDetonador)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDetonadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetonadorActionPerformed

        --valorActual;
        jLabelVisor.setText(String.valueOf(valorActual));
        if (valorActual == 0) {
            jButtonDetonador.setEnabled(false);
            fireBoom();
        }
    }//GEN-LAST:event_jButtonDetonadorActionPerformed

    protected void fireBoom(){
        //crear obj evento
        CuentaAtrasEvent e = new CuentaAtrasEvent(this);
        //recorrer los listeners
        for (CuentaAtrasListener l: listeners) {
            l.boom(e);
        }
        // por cada listener ejecutar metodo "boom"
        
    }    
    
    private ArrayList<CuentaAtrasListener> listeners = new ArrayList();

    public void addCuentaAtrasListener(CuentaAtrasListener l) {
        listeners.add(l);
    }

    public void removeCuentaAtrasListener(CuentaAtrasListener l) {
        listeners.remove(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetonador;
    private javax.swing.JLabel jLabelVisor;
    // End of variables declaration//GEN-END:variables
}
