/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MisComponentes.ComponenteCuentaAtras;

/**
 *
 * @author enrique
 */
public class JFrameTestCuentaAtras extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTestCuentaAtras
     */
    public JFrameTestCuentaAtras() {
        initComponents();
//        jCuentaAtras1.addCuentaAtrasListener(miGestor);
//        jButtonDetonador.setText("Detona en: "+numeroPulsaciones);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelbomba = new javax.swing.JLabel();
        jButtonDetonador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creación de componentes: Cuenta Atrás");

        jLabelbomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisComponentes/ComponenteCuentaAtras/bomba.png"))); // NOI18N
        jLabelbomba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonDetonador.setText("Detona en ...");
        jButtonDetonador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetonadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButtonDetonador, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabelbomba, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabelbomba, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButtonDetonador, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    private int numeroPulsaciones=5;
//    private int pulsaciones=0;
//    
    private void jButtonDetonadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetonadorActionPerformed
//        pulsaciones++;
//        jButtonDetonador.setText("Detona en: "+(numeroPulsaciones-pulsaciones));
//        if(pulsaciones==numeroPulsaciones){
//            jLabelbomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisComponentes/ComponenteCuentaAtras/boom.jpg")));
//            jButtonDetonador.setEnabled(false);
//        }
    }//GEN-LAST:event_jButtonDetonadorActionPerformed

    
    private gestorCA miGestor = new gestorCA();
    
    private class gestorCA implements CuentaAtrasListener{

        @Override
        public void boom(CuentaAtrasEvent evt) {

            System.out.println("BOOM");
            jLabelbomba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisComponentes/ComponenteCuentaAtras/boom.jpg")));

        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTestCuentaAtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTestCuentaAtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTestCuentaAtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTestCuentaAtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTestCuentaAtras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetonador;
    private javax.swing.JLabel jLabelbomba;
    // End of variables declaration//GEN-END:variables
}
