/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Empleados.Empleado;
import Empleados.EmpleadoComision;
import Empleados.EmpleadoHoras;
import Empleados.EmpleadoMontador;
import Empleados.JefeProyecto;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Point;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author enrique
 */
public class JFrameEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form JFrameEmpleados
     */
    public JFrameEmpleados() {
        initComponents();
        initMyComponents();
        datosPrueba();
    }
    private void initMyComponents(){
        jListEmpleados.setModel(Empleado.listaEmpleados);
       // inicializaLayout();
        OwnLayoutManager miLM = new OwnLayoutManager();
       jPanelTrabajadoresAñadidos.setLayout(miLM);
//        jPanelTrabajadoresAñadidos.setLayout(new GridLayout(0,3));
    }
    
    private void datosPrueba(){
            new  EmpleadoHoras("Aitor", "Menta", 25, 12.75);
            new JefeProyecto("Elena", "Nito del Bosque",875.25,1);
            new  EmpleadoMontador("Larry", "Hoja", 30, 11.55);
            new JefeProyecto("Eva", "Lencia",1200.25,5);
            new  EmpleadoHoras("Olga", "Licia", 40, 18.5);
            new JefeProyecto("Ana", "Varra",650,3);
            new  EmpleadoHoras("Monica", "Taluña", 36, 12);
            new EmpleadoComision("Lucia", "Anda", 525.50, 125, 25);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTiposTrabajadores = new javax.swing.ButtonGroup();
        jPanelListadoEmpleados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmpleados = new javax.swing.JList();
        jButtonAñadir = new javax.swing.JButton();
        jPanelTipoTrabajador = new javax.swing.JPanel();
        jRadioButtonJefe = new javax.swing.JRadioButton();
        jRadioButtonPorHoras = new javax.swing.JRadioButton();
        jRadioButtonMontador = new javax.swing.JRadioButton();
        jRadioButtonComision = new javax.swing.JRadioButton();
        jPanelTrabajadoresAñadidos = new javax.swing.JPanel();
        jButtonCalcular = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Empleados");

        jPanelListadoEmpleados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Trabajadores en activo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jListEmpleados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jListEmpleados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListEmpleados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListEmpleadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListEmpleados);

        jButtonAñadir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAñadir.setText("Añadir al panel");
        jButtonAñadir.setEnabled(false);
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListadoEmpleadosLayout = new javax.swing.GroupLayout(jPanelListadoEmpleados);
        jPanelListadoEmpleados.setLayout(jPanelListadoEmpleadosLayout);
        jPanelListadoEmpleadosLayout.setHorizontalGroup(
            jPanelListadoEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListadoEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addGroup(jPanelListadoEmpleadosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAñadir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelListadoEmpleadosLayout.setVerticalGroup(
            jPanelListadoEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListadoEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelTipoTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Trabajadores a mostrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanelTipoTrabajador.setForeground(new java.awt.Color(0, 0, 204));
        jPanelTipoTrabajador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        buttonGroupTiposTrabajadores.add(jRadioButtonJefe);
        jRadioButtonJefe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonJefe.setText("Jefe de Proyecto");
        jRadioButtonJefe.setEnabled(false);

        buttonGroupTiposTrabajadores.add(jRadioButtonPorHoras);
        jRadioButtonPorHoras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonPorHoras.setText("Trabajador por Horas");
        jRadioButtonPorHoras.setEnabled(false);

        buttonGroupTiposTrabajadores.add(jRadioButtonMontador);
        jRadioButtonMontador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonMontador.setText("Trabajador Montador");
        jRadioButtonMontador.setEnabled(false);

        buttonGroupTiposTrabajadores.add(jRadioButtonComision);
        jRadioButtonComision.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonComision.setText("Trabajador a Comisión");
        jRadioButtonComision.setEnabled(false);

        javax.swing.GroupLayout jPanelTipoTrabajadorLayout = new javax.swing.GroupLayout(jPanelTipoTrabajador);
        jPanelTipoTrabajador.setLayout(jPanelTipoTrabajadorLayout);
        jPanelTipoTrabajadorLayout.setHorizontalGroup(
            jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonJefe)
                    .addComponent(jRadioButtonPorHoras)
                    .addGroup(jPanelTipoTrabajadorLayout.createSequentialGroup()
                        .addComponent(jRadioButtonMontador, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(jRadioButtonComision))
                .addGap(22, 22, 22))
        );
        jPanelTipoTrabajadorLayout.setVerticalGroup(
            jPanelTipoTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTipoTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonJefe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPorHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonMontador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonComision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTrabajadoresAñadidos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Trabajadores añadidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanelTrabajadoresAñadidos.setForeground(new java.awt.Color(0, 0, 204));
        jPanelTrabajadoresAñadidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanelTrabajadoresAñadidos.setMaximumSize(new java.awt.Dimension(32767, 378));
        jPanelTrabajadoresAñadidos.setPreferredSize(new java.awt.Dimension(386, 200));
        jPanelTrabajadoresAñadidos.setLayout(null);

        jButtonCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCalcular.setText("Calcular salario seleccionados");

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEliminar.setText("Elimina trabajadores seleccionados");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelTrabajadoresAñadidos, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelListadoEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelTipoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtonCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCalcular, jButtonEliminar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelListadoEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTipoTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTrabajadoresAñadidos, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcular)
                    .addComponent(jButtonEliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        JCheckEmpleado j = new JCheckEmpleado(Empleado.listaEmpleados.get(jListEmpleados.getSelectedIndex()));
        jPanelTrabajadoresAñadidos.add(j,"");
        repaint();
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    private void jListEmpleadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListEmpleadosValueChanged
        jButtonAñadir.setEnabled(jListEmpleados.getSelectedIndex()!=-1);
    }//GEN-LAST:event_jListEmpleadosValueChanged

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed

        for (Component c: jPanelTrabajadoresAñadidos.getComponents()){
            JCheckEmpleado j= (JCheckEmpleado) c;
            if(j.isSelected())jPanelTrabajadoresAñadidos.remove(c);
        }
        repaint();
        revalidate();
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEmpleados().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTiposTrabajadores;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JList jListEmpleados;
    private javax.swing.JPanel jPanelListadoEmpleados;
    private javax.swing.JPanel jPanelTipoTrabajador;
    private javax.swing.JPanel jPanelTrabajadoresAñadidos;
    private javax.swing.JRadioButton jRadioButtonComision;
    private javax.swing.JRadioButton jRadioButtonJefe;
    private javax.swing.JRadioButton jRadioButtonMontador;
    private javax.swing.JRadioButton jRadioButtonPorHoras;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
