/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MisComponentes.JBombilla;

import java.util.Calendar;
import javax.swing.ImageIcon;

/**
 *
 * @author Jesus
 */
public class JBombilla extends javax.swing.JPanel {

    /**
     * Creates new form JBombilla
     */
    public static enum Habitaculos {
        SIN_DEFINIR("SIN DEFINIR"),
        SALON,
        CUARTO_DE_BAÑO("CUARTO DE BAÑO"),
        DORMITORIO_PRINCIPAL("DORMITORIO PRINCIPAL"),
        DORMITORI_INFANTIL("DORMITORIO INFANTIL"),
        COCINA;
        String habitaculo;

        private Habitaculos() {
            this.habitaculo=super.toString();
        }

        private Habitaculos(String habitaculo) {
            this.habitaculo = habitaculo;
        }

        @Override
        public String toString() {
            return this.habitaculo;
        }
    }

    private enum Estado {
        ENCENDIDA,
        APAGADA,
        FUNDIDA;
    }

    private Bombilla bombilla;
    private Habitaculos habitaculo = Habitaculos.SIN_DEFINIR;
    private Estado estado = Estado.APAGADA;
    private int numeroMaximoEncendidos=5;
    private int tiempoMaximoEncendido=15;

    public JBombilla() {
        initComponents();
        iniciaMisComponentes();
    }

    private void iniciaMisComponentes() {
        bombilla = new Bombilla();
        jLabelReponer.setVisible(false);
        consistencia();
    }

    private void consistencia() {
        jLabelBombilla.setIcon(new ImageIcon(getClass().getResource((estado == Estado.ENCENDIDA) ? "/Recursos/encendida.png" : "/Recursos/apagada.png")));
        jButtonEncendidoApagado.setText((estado == Estado.APAGADA) ? "ON" : "OFF");
        jButtonEncendidoApagado.setEnabled(estado != Estado.FUNDIDA);
        jLabelReponer.setVisible(estado==Estado.FUNDIDA);
        
    }

    public void encender(){
        estado= Estado.ENCENDIDA;
        bombilla.setEncendida();
        System.out.println(bombilla.getNumeroEncendidos()+"------"+bombilla.getTiempoEncendida());
        consistencia();
    }
   
    public void apagar(){
        estado= Estado.APAGADA;
        bombilla.setApagada();
        comprobarVidaUtil();
        consistencia();
    }
    
    public void reponer(){
        bombilla=new Bombilla();
        estado= Estado.APAGADA;
        consistencia();
    }
    
    private void comprobarVidaUtil(){
        if(bombilla.getNumeroEncendidos()>numeroMaximoEncendidos||bombilla.getTiempoEncendida()>tiempoMaximoEncendido)estado=Estado.FUNDIDA;
    }
    
    
    
    private class Bombilla {

        private int numeroEncendidos = 0;
        private long tiempoEncendida = 0;
        private long inicioTiempoEncendida;

        public void setEncendida() {
            inicioTiempoEncendida = Calendar.getInstance().getTimeInMillis();
        }

        public void setApagada() {
            this.numeroEncendidos++;
            tiempoEncendida += Calendar.getInstance().getTimeInMillis() - inicioTiempoEncendida;
        }

        public int getNumeroEncendidos() {
            return numeroEncendidos;
        }

        public long getTiempoEncendida() {
            return tiempoEncendida/1000;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBombilla = new javax.swing.JLabel();
        jLabelHabitaculo = new javax.swing.JLabel();
        jLabelNumeroBombillaHabitaculo = new javax.swing.JLabel();
        jButtonEncendidoApagado = new javax.swing.JButton();
        jLabelReponer = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 255));

        jLabelBombilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/apagada.png"))); // NOI18N

        jLabelHabitaculo.setBackground(new java.awt.Color(153, 255, 153));
        jLabelHabitaculo.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabelHabitaculo.setForeground(new java.awt.Color(255, 255, 0));
        jLabelHabitaculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHabitaculo.setText("jLabel1");

        jLabelNumeroBombillaHabitaculo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNumeroBombillaHabitaculo.setForeground(new java.awt.Color(255, 0, 51));
        jLabelNumeroBombillaHabitaculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumeroBombillaHabitaculo.setText("0");
        jLabelNumeroBombillaHabitaculo.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true), null));

        jButtonEncendidoApagado.setFont(new java.awt.Font("Minion Pro SmBd", 0, 24)); // NOI18N
        jButtonEncendidoApagado.setText("ON");
        jButtonEncendidoApagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncendidoApagadoActionPerformed(evt);
            }
        });

        jLabelReponer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelReponer.setForeground(new java.awt.Color(0, 255, 0));
        jLabelReponer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelReponer.setText("REPONER");
        jLabelReponer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReponerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBombilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumeroBombillaHabitaculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEncendidoApagado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelReponer, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                    .addComponent(jLabelHabitaculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHabitaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBombilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNumeroBombillaHabitaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEncendidoApagado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelReponer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEncendidoApagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncendidoApagadoActionPerformed
        if(estado==Estado.APAGADA)encender();
        else apagar();
        System.out.println(estado);
    }//GEN-LAST:event_jButtonEncendidoApagadoActionPerformed

    private void jLabelReponerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReponerMouseClicked
        reponer();
    }//GEN-LAST:event_jLabelReponerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEncendidoApagado;
    private javax.swing.JLabel jLabelBombilla;
    private javax.swing.JLabel jLabelHabitaculo;
    private javax.swing.JLabel jLabelNumeroBombillaHabitaculo;
    private javax.swing.JLabel jLabelReponer;
    // End of variables declaration//GEN-END:variables
}
