/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//7.5

package ComponenteJCandado;

import java.awt.ActiveEvent;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.EventObject;
import javax.swing.JButton;

/**
 *
 * @author usuario
 */
public class JCandado extends javax.swing.JPanel {

    /**
     * Creates new form JCandado
     */
    
    private enum Estados{
        ABIERTO,
        CERRADO,
        BLOQUEADO;
    }
    
    private static int numeroIdCandado;
    private String idCandado;
    private JCandadoListener listener=null;
    
    private String contraseña="1111";
    private final int numeroMaxContraseñaErronea=3;
    private Estados estado=Estados.ABIERTO;
    private int intentosApertura=0;
    
    public JCandado() {
        initComponents();
        initMyComponents();
    }
    
    public JCandado(String identificador) {
        initComponents();
        initMyComponents();
        setIdCandado(identificador);
    }

    public String getIdCandado() {
        return idCandado;
    }

    public void setIdCandado(String idCandado) {
        if(idCandado!=null)return;
        this.idCandado = idCandado+"_"+numeroIdCandado;
        jLabelIdCandado.setText(this.idCandado);
    }

    public JCandadoListener getListener() {
        return listener;
    }

    public void setListener(JCandadoListener listener) {
        if(this.listener!=null)return;
        this.listener = listener;
        System.out.println("Listener");
    }
    
    public void abrir(){
        if(++intentosApertura>numeroMaxContraseñaErronea){
            setEstado(Estados.BLOQUEADO);
            listener.bloqueado(new JCandadoEvent(this));
            return;
        }
        setEstado(Estados.ABIERTO);
    }
    
    public void cerrar(){
        setEstado(Estados.CERRADO);
    }
    
    public void desbloquear(){
        setEstado(Estados.ABIERTO);
    }
    
    private void setEstado(Estados estado){
        switch(estado){
            case ABIERTO:
                if(this.estado==Estados.BLOQUEADO){
                    bloquearDesbloquearCandado(false);
                    return;
                }
                if(this.estado==Estados.CERRADO){
                    if(!comprobarContraseña()){
                        jLabelVisor.setText("ERROR");
                        return;
                    }
                    jPanelIndicadorAbierto.setOpaque(true);
                    jPanelIndicadorCerrado.setOpaque(false);
                }
                if(this.estado==Estados.ABIERTO){
                    return;
                }
                break;
            case CERRADO:
                System.out.println("cerrado arriba");
                if(this.estado==Estados.CERRADO)return;
                if(this.estado==Estados.ABIERTO){
                    System.out.println("asda");
                    jPanelIndicadorAbierto.setOpaque(false);
                    jPanelIndicadorCerrado.setOpaque(true);
                }
                break;
            case BLOQUEADO:
                bloquearDesbloquearCandado(true);
                break;
        }
        this.estado=estado;
    }
    
    private void initMyComponents(){
        gestorTecaldo gestTeclas= new gestorTecaldo();
        for (Component c: jPanelTeclado.getComponents()) {
            ((JButton)c).addActionListener(gestTeclas);
        }
        jButtonAbrir.setText("cerrado");
        jPanelIndicadorAbierto.setOpaque(true);
        jPanelIndicadorCerrado.setOpaque(false);
        jPanelTeclado.getComponents();
        numeroIdCandado++;
    }
    
    private void bloquearDesbloquearCandado(boolean bloquear){
        jLabelVisor.setText((bloquear)?"Locked":"");
        for (Component c: this.getComponents()) {
            c.setEnabled(bloquear);
        }
    }
    
    private boolean comprobarContraseña(){
        return contraseña.equals(jLabelVisor.getText());
    }
    
    private class gestorTecaldo implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            jLabelVisor.setText(((JButton)e.getSource()).getText());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTeclado = new javax.swing.JPanel();
        jButtonTeclaDos = new javax.swing.JButton();
        jButtonTeclaUno1 = new javax.swing.JButton();
        jButtonTecla3 = new javax.swing.JButton();
        jButtonTeclaCuatro = new javax.swing.JButton();
        jLabelVisor = new javax.swing.JLabel();
        jPanelIndicadorAbierto = new javax.swing.JPanel();
        jPanelIndicadorCerrado = new javax.swing.JPanel();
        jLabelIdCandado = new javax.swing.JLabel();
        jButtonContraseña = new javax.swing.JButton();
        jButtonSeleccionar = new javax.swing.JButton();
        jButtonAbrir = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonTeclaDos.setText("2");

        jButtonTeclaUno1.setText("1");

        jButtonTecla3.setText("3");

        jButtonTeclaCuatro.setText("4");

        javax.swing.GroupLayout jPanelTecladoLayout = new javax.swing.GroupLayout(jPanelTeclado);
        jPanelTeclado.setLayout(jPanelTecladoLayout);
        jPanelTecladoLayout.setHorizontalGroup(
            jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTecladoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTeclaUno1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTeclaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTecla3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTeclaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelTecladoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonTecla3, jButtonTeclaCuatro, jButtonTeclaDos, jButtonTeclaUno1});

        jPanelTecladoLayout.setVerticalGroup(
            jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTecladoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonTecla3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelTecladoLayout.createSequentialGroup()
                .addGroup(jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonTeclaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonTeclaUno1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonTeclaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelTecladoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonTecla3, jButtonTeclaCuatro, jButtonTeclaDos, jButtonTeclaUno1});

        jLabelVisor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelVisor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelVisor.setForeground(new java.awt.Color(0, 255, 51));
        jLabelVisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVisor.setText("Visor");
        jLabelVisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelVisor.setOpaque(true);

        jPanelIndicadorAbierto.setBackground(new java.awt.Color(0, 255, 0));
        jPanelIndicadorAbierto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelIndicadorAbiertoLayout = new javax.swing.GroupLayout(jPanelIndicadorAbierto);
        jPanelIndicadorAbierto.setLayout(jPanelIndicadorAbiertoLayout);
        jPanelIndicadorAbiertoLayout.setHorizontalGroup(
            jPanelIndicadorAbiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanelIndicadorAbiertoLayout.setVerticalGroup(
            jPanelIndicadorAbiertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanelIndicadorCerrado.setBackground(new java.awt.Color(255, 0, 0));
        jPanelIndicadorCerrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelIndicadorCerradoLayout = new javax.swing.GroupLayout(jPanelIndicadorCerrado);
        jPanelIndicadorCerrado.setLayout(jPanelIndicadorCerradoLayout);
        jPanelIndicadorCerradoLayout.setHorizontalGroup(
            jPanelIndicadorCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        jPanelIndicadorCerradoLayout.setVerticalGroup(
            jPanelIndicadorCerradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabelIdCandado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIdCandado.setText("id");
        jLabelIdCandado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonContraseña.setText("Contraseña");
        jButtonContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContraseñaActionPerformed(evt);
            }
        });

        jButtonSeleccionar.setText("Seleccionar");
        jButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarActionPerformed(evt);
            }
        });

        jButtonAbrir.setText("Abrir");
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelIdCandado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanelIndicadorCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelIndicadorAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonContraseña, jButtonSeleccionar});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanelIndicadorAbierto, jPanelIndicadorCerrado});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelIndicadorCerrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVisor, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jPanelIndicadorAbierto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelIdCandado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonContraseña)
                    .addComponent(jButtonSeleccionar)
                    .addComponent(jButtonAbrir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        
        jButtonAbrir.setText((this.estado==Estados.ABIERTO||this.estado==Estados.BLOQUEADO)?"Cerrar":"Abrir");
        if(this.estado==Estados.ABIERTO)cerrar();
        else abrir();
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButtonContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContraseñaActionPerformed
        if(this.estado!=Estados.ABIERTO)return;
        this.contraseña=jLabelVisor.getText();
    }//GEN-LAST:event_jButtonContraseñaActionPerformed

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarActionPerformed
        listener.seleccionado(new JCandadoEvent(this));
    }//GEN-LAST:event_jButtonSeleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonContraseña;
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JButton jButtonTecla3;
    private javax.swing.JButton jButtonTeclaCuatro;
    private javax.swing.JButton jButtonTeclaDos;
    private javax.swing.JButton jButtonTeclaUno1;
    private javax.swing.JLabel jLabelIdCandado;
    private javax.swing.JLabel jLabelVisor;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelIndicadorAbierto;
    private javax.swing.JPanel jPanelIndicadorCerrado;
    private javax.swing.JPanel jPanelTeclado;
    // End of variables declaration//GEN-END:variables
}
