/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ComponenteJBombilla;

import javax.swing.ImageIcon;


/**
 *
 * @author Jesus
 */
public class JBombilla extends javax.swing.JPanel {

    /**
     * Creates new form JBombilla
     */
    
    private enum Estados{
        ENCENDIDA,
        APAGADA,
        GASTADA;
    }
    
    private int encendidosMaximos=5;
    private String ubicacion;
    
    private Estados estado;
    private int numeroEncendidos;
    private BombillaEscuchador listener;
    
    public JBombilla(String ubicacion, BombillaEscuchador listener) {
        initComponents();
        this.listener=listener;
        setUbicacion(ubicacion);
        setEstado(Estados.APAGADA);
    }

    public int getEncendidosMaximos() {
        return encendidosMaximos;
    }

    public void setEncendidosMaximos(int encendidosMaximos) {
        this.encendidosMaximos = encendidosMaximos;
    }

    public String getUbicacion() {
        return ubicacion;
    }

    private void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
        jLabelUbicacion.setText(ubicacion);
    }
    
    private void setEstado(Estados estado){
        this.estado=estado;
        switch(estado){
            case ENCENDIDA:
                if(++ this.numeroEncendidos>this.encendidosMaximos){
                    setEstado(Estados.GASTADA);
                    return;
                }
                listener.encendida(new BombillaEvento(this,numeroEncendidos));
                consistencia();
                break;
            case APAGADA:
                consistencia();
                break;
            case GASTADA:
                listener.agotada(new BombillaEvento(this));
                consistencia();
                break;
        }
    }
    
    private void consistencia(){
        jLabelBombillaImagen.setIcon(new ImageIcon(getClass().getResource((estado == Estados.ENCENDIDA) ? "/Recursos/encendida.png" : "/Recursos/apagada.png")));
        jButtonEncenderApagar.setText((estado==Estados.APAGADA)?"ON":(estado==Estados.GASTADA)?"X":"OFF");
        this.setEnabled(estado==Estados.GASTADA);
    }
    
    public void encender(){
        if(estado==Estados.ENCENDIDA || estado==Estados.GASTADA)return;
        setEstado(Estados.ENCENDIDA);
    }

    public void apagar(){
        if(estado==Estados.APAGADA || estado==Estados.GASTADA)return;
        setEstado(Estados.APAGADA);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUbicacion = new javax.swing.JLabel();
        jLabelBombillaImagen = new javax.swing.JLabel();
        jButtonEncenderApagar = new javax.swing.JButton();

        jLabelBombillaImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/apagada.png"))); // NOI18N

        jButtonEncenderApagar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonEncenderApagar.setText("ON");
        jButtonEncenderApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncenderApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBombillaImagen)
                        .addGap(25, 25, 25)
                        .addComponent(jButtonEncenderApagar, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBombillaImagen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButtonEncenderApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEncenderApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncenderApagarActionPerformed
        if(estado==Estados.APAGADA)
            encender();
        else
            apagar();
    }//GEN-LAST:event_jButtonEncenderApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEncenderApagar;
    private javax.swing.JLabel jLabelBombillaImagen;
    private javax.swing.JLabel jLabelUbicacion;
    // End of variables declaration//GEN-END:variables
}
