/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import java.util.Random;

/**
 *
 * @author Jesus
 */
public class Buscaminas extends javax.swing.JFrame {

    /**
     * Creates new form Buscaminas
     */
    String [][] tablero = new String[8][8];
    public Buscaminas() {
        initComponents();
        cargarTablero();
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                System.out.print(tablero[i][j]+" ");
            }
            System.out.println("");
        }
    }
    
    public void cargarTablero(){
        Random r= new Random();
        for (int i = 0; i < 10;) {
            int columna = r.nextInt(7);
            int fila= r.nextInt(7);
            if(tablero[fila][columna]==null){
                tablero[fila][columna]="*";
                i++;
            }
        }
        completarTablero();
    }
    
    void completarTablero(){
        for (int i = 0; i < tablero.length; i++) 
            for (int j = 0; j < tablero.length; j++) 
                compruebaMinasAlrededor(i,j);
    }
    
    void compruebaMinasAlrededor(int i, int j){
      int numeroMinas=0;
      if("*".equals(tablero[i][j]))return;
        for (int k = 0; k < 8; k++) {
            try {
                switch(k){
                    case 0:
                        if("*".equals(tablero[i-1][j]))numeroMinas++;
                        break;
                    case 1:
                        if("*".equals(tablero[i-1][j-1]))numeroMinas++;
                        break;
                    case 2:
                        if("*".equals(tablero[i][j-1]))numeroMinas++;
                        break;
                    case 3:
                        if("*".equals(tablero[i+1][j-1]))numeroMinas++;
                        break;
                    case 4:
                        if("*".equals(tablero[i+1][j]))numeroMinas++;
                        break;
                    case 5:
                        if("*".equals(tablero[i+1][j+1]))numeroMinas++;
                        break;
                    case 6:
                        if("*".equals(tablero[i][j+1]))numeroMinas++;
                        break;
                    case 7:
                        if("*".equals(tablero[i-1][j+1]))numeroMinas++;
                        break;
                }
            }catch (Exception e) {}
        }
        tablero[i][j]=String.valueOf(numeroMinas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscaminas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
