INSERT INTO departamentos VALUES (10, 'CONTABILIDAD', 'SEVILLA');
INSERT INTO departamentos VALUES (20, 'INVESTIGACION', 'MADRID');
INSERT INTO departamentos VALUES (30, 'VENTAS', 'BARCELONA');
INSERT INTO departamentos VALUES (40, 'PRODUCCION', 'BILBAO');
