/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import MisComponentes.ComponenteAlarma.JAlarmaEvent;
import MisComponentes.ComponenteAlarma.JAlarmaListener;
import MisComponentes.ComponenteAlarma.JComponenteAlarma;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class JFrameTest extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTest
     */
    
    public JFrameTest() {
        initComponents();
        jComponenteAlarma1.addJAlarmaListener(new gestorAlarma());
        jListSucesos.setModel(eventos);
    }
    
    DefaultListModel eventos=new DefaultListModel();
    
    private class gestorAlarma implements JAlarmaListener{

        @Override
        public void alarmaActivada(JAlarmaEvent evt) {
            eventos.addElement(evt);
        }

        @Override
        public void alarmaDisparada(JAlarmaEvent evt) {
            eventos.addElement(evt);
        }

        @Override
        public void alarmaDesactivada(JAlarmaEvent evt) {
            eventos.addElement(evt);
            
            if(evt.getIntendosDesbloqueoFallidos()!=0)
                jLabelErrorDesactivavion.setText("Intento fallido: "+evt.getIntendosDesbloqueoFallidos()+" de: "+((JComponenteAlarma)evt.getSource()).getMaximoContraseñaIncorrecta());
            else
                jLabelErrorDesactivavion.setText("");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelZonaJardin = new javax.swing.JPanel();
        jLabelJardin = new javax.swing.JLabel();
        jPanelZonaVivienda = new javax.swing.JPanel();
        jLabelVivienda = new javax.swing.JLabel();
        jComponenteAlarma1 = new MisComponentes.ComponenteAlarma.JComponenteAlarma();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSucesos = new javax.swing.JList<>();
        jLabelRegistroSucesos = new javax.swing.JLabel();
        jLabelErrorDesactivavion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonActivar = new javax.swing.JButton();
        jButtonHabilitaDeshabilita = new javax.swing.JButton();
        jButtonCambiaCodigo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelZonaJardin.setBackground(new java.awt.Color(0, 204, 0));
        jPanelZonaJardin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelZonaJardin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelZonaJardinMouseEntered(evt);
            }
        });

        jLabelJardin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelJardin.setForeground(new java.awt.Color(255, 0, 0));
        jLabelJardin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJardin.setText("Zona 1: Jardin");

        jPanelZonaVivienda.setBackground(new java.awt.Color(255, 0, 0));
        jPanelZonaVivienda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelZonaVivienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelZonaViviendaMouseEntered(evt);
            }
        });

        jLabelVivienda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelVivienda.setForeground(new java.awt.Color(0, 204, 0));
        jLabelVivienda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVivienda.setText("Zona 2: Vivienda");

        javax.swing.GroupLayout jPanelZonaViviendaLayout = new javax.swing.GroupLayout(jPanelZonaVivienda);
        jPanelZonaVivienda.setLayout(jPanelZonaViviendaLayout);
        jPanelZonaViviendaLayout.setHorizontalGroup(
            jPanelZonaViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZonaViviendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVivienda, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelZonaViviendaLayout.setVerticalGroup(
            jPanelZonaViviendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZonaViviendaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVivienda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelZonaJardinLayout = new javax.swing.GroupLayout(jPanelZonaJardin);
        jPanelZonaJardin.setLayout(jPanelZonaJardinLayout);
        jPanelZonaJardinLayout.setHorizontalGroup(
            jPanelZonaJardinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZonaJardinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelJardin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelZonaJardinLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanelZonaVivienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66))
        );
        jPanelZonaJardinLayout.setVerticalGroup(
            jPanelZonaJardinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZonaJardinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelJardin)
                .addGap(18, 18, 18)
                .addComponent(jPanelZonaVivienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(58, 58, 58))
        );

        jListSucesos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListSucesosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListSucesos);

        jLabelRegistroSucesos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRegistroSucesos.setText("Registro de Sucesos.");

        jLabelErrorDesactivavion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelErrorDesactivavion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gestion Componente"));

        jButtonActivar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonActivar.setText("Activar/Desactivar codigo \"AAA\"");
        jButtonActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActivarActionPerformed(evt);
            }
        });

        jButtonHabilitaDeshabilita.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonHabilitaDeshabilita.setText("Habilitar/Deshabilitar");
        jButtonHabilitaDeshabilita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabilitaDeshabilitaActionPerformed(evt);
            }
        });

        jButtonCambiaCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCambiaCodigo.setText("Cambiar codigo \"AAA\"- \"BBB\"");
        jButtonCambiaCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCambiaCodigoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Numero Maximo=5");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCambiaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButtonHabilitaDeshabilita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonActivar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButtonCambiaCodigo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonActivar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonHabilitaDeshabilita, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCambiaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonActivar, jButtonHabilitaDeshabilita});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButtonCambiaCodigo});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRegistroSucesos, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jLabelErrorDesactivavion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComponenteAlarma1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelZonaJardin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComponenteAlarma1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelZonaJardin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorDesactivavion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRegistroSucesos, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListSucesosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListSucesosValueChanged
        JAlarmaEvent alarmaEvento = ((JAlarmaEvent)eventos.get(jListSucesos.getSelectedIndex()));
        JOptionPane.showMessageDialog(null, "ACCION: "+alarmaEvento.getAccionEvento()+
                "\nFECHA: "+alarmaEvento.getFecha()+
                "\nLugar: "+alarmaEvento.getZona());
    }//GEN-LAST:event_jListSucesosValueChanged

    private void jPanelZonaViviendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelZonaViviendaMouseEntered
        jComponenteAlarma1.activarSensorZona2();
    }//GEN-LAST:event_jPanelZonaViviendaMouseEntered

    private void jPanelZonaJardinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelZonaJardinMouseEntered
        jComponenteAlarma1.activarSensorZona1();
    }//GEN-LAST:event_jPanelZonaJardinMouseEntered

    private void jButtonActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActivarActionPerformed
        if(!jComponenteAlarma1.isAlarmaActiva())
            jComponenteAlarma1.activar("AAA");
        else
            jComponenteAlarma1.desactivar("AAA");
    }//GEN-LAST:event_jButtonActivarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jComponenteAlarma1.setMaximoContraseñaIncorrecta(5);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonHabilitaDeshabilitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabilitaDeshabilitaActionPerformed
        jComponenteAlarma1.setEnabled(true);
    }//GEN-LAST:event_jButtonHabilitaDeshabilitaActionPerformed

    private void jButtonCambiaCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCambiaCodigoActionPerformed
        jComponenteAlarma1.cambiarContraseña("AAA","BBB");
    }//GEN-LAST:event_jButtonCambiaCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonActivar;
    private javax.swing.JButton jButtonCambiaCodigo;
    private javax.swing.JButton jButtonHabilitaDeshabilita;
    private MisComponentes.ComponenteAlarma.JComponenteAlarma jComponenteAlarma1;
    private javax.swing.JLabel jLabelErrorDesactivavion;
    private javax.swing.JLabel jLabelJardin;
    private javax.swing.JLabel jLabelRegistroSucesos;
    private javax.swing.JLabel jLabelVivienda;
    private javax.swing.JList<String> jListSucesos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelZonaJardin;
    private javax.swing.JPanel jPanelZonaVivienda;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
