/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author enrique
 */
public class JFrameCardLayout extends javax.swing.JFrame {
    private JButton bt1;
    private JButton bt2;
    private JButton bt3;
    private JButton bt4;
    private JButton bt5;
    /**
     * Creates new form JFrameBorderLayout
     */
    public JFrameCardLayout() {
        initComponents();
        initMyComponents();
        setupLayoutManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Card");
        setMinimumSize(new java.awt.Dimension(10, 150));
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 */
    private JPanel card1;
    private JPanel card2;
    private JPanel cards;
    final static String PANEL_UNO = "Card con dos botones";
    final static String PANEL_DOS = "Card con tres botones";    
    private JPanel comboBoxPane;
    private JComboBox cb;
    private void initMyComponents(){
        //creamos los paneles para las cards que aparecen y desaparecen
        card1=new JPanel();
        card1.setBorder(javax.swing.BorderFactory.createTitledBorder(PANEL_UNO));
        card2=new JPanel();
        card2.setBorder(javax.swing.BorderFactory.createTitledBorder(PANEL_DOS));
        
        //creamos la combo que permite elegir el panel a visualizar
        String comboBoxItems[] = { PANEL_UNO, PANEL_DOS };
        cb = new JComboBox(comboBoxItems);
        cb.setEditable(false);
        gestorCards miGestor=new gestorCards();
        cb.addItemListener(miGestor);
        
        //creamos los botones
        bt1=new JButton("boton uno");
        bt2=new JButton("boton dos");
        bt3=new JButton("boton tres");
        bt4=new JButton("boton cuatro");
        bt5=new JButton("boton cinco");
        this.setSize(400, 300);

    }
    
    private void setupLayoutManager(){
        //creamos el panel que contendrá las cards
        cards=new JPanel(new CardLayout());

        //creamos la combobox dentro de un panel para que no se solape con las cards
        comboBoxPane = new JPanel(); 
        comboBoxPane.add(cb);
        
        //añadimos los botones a los respectivos paneles
        card1.add(bt1);
        card1.add(bt2);
        card2.add(bt3);
        card2.add(bt4);
        card2.add(bt5);
        
        //añadimos las cards al panel principal
        cards.add(card1,PANEL_UNO );
        cards.add(card2, PANEL_DOS);
        
        //y por último añadimos los dos paneles al jFrame
        this.add(comboBoxPane, BorderLayout.NORTH);
        this.add(cards, BorderLayout.CENTER);
    }
    private class gestorCards implements ItemListener{

        @Override
        public void itemStateChanged(ItemEvent ie) {
            CardLayout cl = (CardLayout)(cards.getLayout());
            cl.show(cards, (String)ie.getItem());            
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCardLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCardLayout().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
