/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author enrique
 */
public class JFrameBorderLayout extends javax.swing.JFrame {
    private JButton bt1;
    private JButton bt2;
    private JButton bt3;
    private JButton bt4;
    private JButton bt5;
    /**
     * Creates new form JFrameBorderLayout
     */
    public JFrameBorderLayout() {
        initComponents();
        initMyComponents();
        setupLayoutManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Border");
        setMinimumSize(new java.awt.Dimension(10, 150));
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 */
    private void initMyComponents(){
        bt1=new JButton("boton uno");
        bt2=new JButton("boton dos");
        bt3=new JButton("boton tres");
        bt4=new JButton("boton cuatro");
        bt5=new JButton("boton cinco");
//        bt1.setPreferredSize(new java.awt.Dimension(1,100));
//        bt3.setPreferredSize(new java.awt.Dimension(500,200));
        this.setSize(400, 300);
        gestorBt miGestor=new gestorBt();
        bt1.addActionListener(miGestor);
        bt2.addActionListener(miGestor);
        bt3.addActionListener(miGestor);
        bt4.addActionListener(miGestor);
        bt5.addActionListener(miGestor);
        
    }
    
    private void setupLayoutManager(){
        this.setLayout(new BorderLayout(20,5));
        this.add(bt1,BorderLayout.NORTH);
        this.add(bt2,BorderLayout.SOUTH);
        this.add(bt3,BorderLayout.WEST);
        this.add(bt4,BorderLayout.EAST);
        this.add(bt5,BorderLayout.CENTER);
    }
    private class gestorBt implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent ae) {
            JButton bt=(JButton)ae.getSource();
            bt.setVisible(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBorderLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBorderLayout().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
