/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import ComponenteJPulsador.JPulsador;
import ComponenteJPulsador.PulsadorEvent;
import ComponenteJPulsador.PulsadorListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Jesus
 */
public class JFrameTest extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTest
     */
    
    private ArrayList lista_pulsadores= new ArrayList();
    private DefaultListModel gastados= new DefaultListModel();
    
    public JFrameTest() {
        initComponents();
        iniciaMisComponentes();
    }
    
    private void iniciaMisComponentes(){
        jListGastados.setModel(gastados);
        consistencia();
    }
    
    private class gestorPulsador implements PulsadorListener{

        @Override
        public void gastado(PulsadorEvent evt) {
            gastados.addElement(evt);
        }
        
    }
    private void consistencia(){
        jPanelPulsadoresCreados.repaint();
        jPanelPulsadoresCreados.revalidate();
        jButtonPulsarTodos.setEnabled(lista_pulsadores.size()>0);
        jButtonReset.setEnabled(jListGastados.getSelectedIndex()!=-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPulsadoresCreados = new javax.swing.JPanel();
        jPanelPulsadoresGastados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListGastados = new javax.swing.JList<>();
        jButtonReset = new javax.swing.JButton();
        jButtonNuevoPulsador = new javax.swing.JButton();
        jButtonPulsarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPulsadoresCreados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pulsadores"));

        jPanelPulsadoresGastados.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pulsadores Gastados"));

        jListGastados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListGastadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListGastados);

        jButtonReset.setText("Resetear Seleccionado");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPulsadoresGastadosLayout = new javax.swing.GroupLayout(jPanelPulsadoresGastados);
        jPanelPulsadoresGastados.setLayout(jPanelPulsadoresGastadosLayout);
        jPanelPulsadoresGastadosLayout.setHorizontalGroup(
            jPanelPulsadoresGastadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPulsadoresGastadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPulsadoresGastadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPulsadoresGastadosLayout.setVerticalGroup(
            jPanelPulsadoresGastadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPulsadoresGastadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jButtonNuevoPulsador.setText("Nuevo Pulsador");
        jButtonNuevoPulsador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoPulsadorActionPerformed(evt);
            }
        });

        jButtonPulsarTodos.setText("Pulsar Todos");
        jButtonPulsarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPulsarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPulsadoresCreados, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPulsadoresGastados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNuevoPulsador, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPulsarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonNuevoPulsador, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButtonPulsarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelPulsadoresGastados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPulsadoresCreados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoPulsadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoPulsadorActionPerformed
        JPulsador pulsador = new JPulsador();
        lista_pulsadores.add(pulsador);
        jPanelPulsadoresCreados.add(pulsador);
        pulsador.setListener(new gestorPulsador());
        consistencia();
    }//GEN-LAST:event_jButtonNuevoPulsadorActionPerformed

    private void jButtonPulsarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPulsarTodosActionPerformed
        for(Object p: lista_pulsadores){
            ((JPulsador)p).pulsar();
        }
        consistencia();
    }//GEN-LAST:event_jButtonPulsarTodosActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
       
       for(Object o: jListGastados.getSelectedValues()){
           ((JPulsador)(((PulsadorEvent)o).getSource())).reset();
           gastados.removeElement(o);
       }
        
        
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jListGastadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListGastadosValueChanged
        consistencia();
    }//GEN-LAST:event_jListGastadosValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNuevoPulsador;
    private javax.swing.JButton jButtonPulsarTodos;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JList<String> jListGastados;
    private javax.swing.JPanel jPanelPulsadoresCreados;
    private javax.swing.JPanel jPanelPulsadoresGastados;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
