/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ComponenteJPulsador;

import java.util.Calendar;

/**
 *
 * @author Jesus
 */
public class JPulsador extends javax.swing.JPanel {

    /**
     * Creates new form JPulsador
     */
    private static int numeroPulsadores=0;
    
    private int pulsaciones;
    private int maxPulsaciones=5;
    private int idPulsador;
    private String strIdPulsador;
    private PulsadorListener listener;
    
    
    public JPulsador() {
        initComponents();
        setIdPulsador();
        
    }

    public int getMaxPulsaciones() {
        return maxPulsaciones;
    }

    public void setMaxPulsaciones(int maxPulsaciones) {
        this.maxPulsaciones = maxPulsaciones;
    }

    public int getIdPulsador() {
        return idPulsador;
    }
    
    public void setListener(PulsadorListener l){
        if(listener!=null)return;
        this.listener=l;
    }

    private void setIdPulsador(){
        this.strIdPulsador="-"+(++numeroPulsadores);
        jLabelId.setText(strIdPulsador);
    }
    
    public void pulsar(){
        if((this.pulsaciones>maxPulsaciones))return;
        if(++this.pulsaciones>maxPulsaciones){
            listener.gastado(new PulsadorEvent(this));
            consistencia();
            return;
        }
        jLabelVisor.setText(String.valueOf(this.pulsaciones));
        consistencia();
    }
    
    public void reset(){
        pulsaciones=0;
        jLabelVisor.setText(String.valueOf(this.pulsaciones));
        consistencia();
    }
    
    private void consistencia(){
        System.out.println(this.pulsaciones);
        System.out.println(this.pulsaciones>maxPulsaciones);
        jButtonPulsacion.setEnabled(!(this.pulsaciones>maxPulsaciones));
        jLabelId.setEnabled(!(this.pulsaciones>maxPulsaciones));
        jLabelVisor.setEnabled(!(this.pulsaciones>maxPulsaciones));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelVisor = new javax.swing.JLabel();
        jButtonPulsacion = new javax.swing.JButton();
        jLabelId = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelVisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVisor.setText("jLabel1");

        jButtonPulsacion.setText("Pulsame");
        jButtonPulsacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPulsacionActionPerformed(evt);
            }
        });

        jLabelId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelId.setText("id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonPulsacion, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jLabelVisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPulsacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelId)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPulsacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPulsacionActionPerformed
        pulsar();
    }//GEN-LAST:event_jButtonPulsacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPulsacion;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelVisor;
    // End of variables declaration//GEN-END:variables
}
