/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import MisComponentes.JBombilla.JBombilla;
import javafx.scene.control.RadioButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author usuario
 */
public class JFrameTestBombillas extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTestBombillas
     */
    public JFrameTestBombillas() {
        initComponents();
        iniciaMisComponenetes();
    }

    private void iniciaMisComponenetes(){
        jComboBoxUbicaciones.setModel(new DefaultComboBoxModel(JBombilla.Ubicaciones.values()));
        cargarRadioButton();
    }
    
    private void cargarRadioButton(){
//        Radion bG= new ButtonGroup();
        for (JBombilla.Ubicaciones u : JBombilla.Ubicaciones.values()) {
            RadioButton rb = new RadioButton(u.toString());
            bG.add(rb);
        }
    }
    
    private void consistencia(){
        jPanelBombillas.repaint();
        jPanelUbicaciones.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBombillas = new javax.swing.JPanel();
        jBombilla1 = new MisComponentes.JBombilla.JBombilla();
        jPanelUbicaciones = new javax.swing.JPanel();
        jButtonApagar = new javax.swing.JButton();
        jButtonEncender = new javax.swing.JButton();
        jComboBoxUbicaciones = new javax.swing.JComboBox<>();
        jButtonNuevaBombilla = new javax.swing.JButton();
        jLabelUbicacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBombillasReponer = new javax.swing.JList<>();
        jButtonReponer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBombillas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bombillas"));
        jPanelBombillas.add(jBombilla1);

        jPanelUbicaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ubicaciones"));

        jButtonApagar.setText("Apagar");

        jButtonEncender.setText("Encender");

        javax.swing.GroupLayout jPanelUbicacionesLayout = new javax.swing.GroupLayout(jPanelUbicaciones);
        jPanelUbicaciones.setLayout(jPanelUbicacionesLayout);
        jPanelUbicacionesLayout.setHorizontalGroup(
            jPanelUbicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUbicacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonEncender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButtonApagar)
                .addContainerGap())
        );
        jPanelUbicacionesLayout.setVerticalGroup(
            jPanelUbicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUbicacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelUbicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonApagar)
                    .addComponent(jButtonEncender))
                .addContainerGap())
        );

        jComboBoxUbicaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonNuevaBombilla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonNuevaBombilla.setText("Nueva Bombilla");
        jButtonNuevaBombilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaBombillaActionPerformed(evt);
            }
        });

        jLabelUbicacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUbicacion.setText("Ubicación:");

        jScrollPane1.setViewportView(jListBombillasReponer);

        jButtonReponer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonReponer.setText("REPONER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBombillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(234, 234, 234))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNuevaBombilla, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxUbicaciones, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(522, 522, 522)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonReponer, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanelUbicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelUbicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBombillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxUbicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonReponer)
                    .addComponent(jButtonNuevaBombilla))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevaBombillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaBombillaActionPerformed
        jPanelBombillas.add(new JBombilla((JBombilla.Ubicaciones)jComboBoxUbicaciones.getSelectedItem()));
        consistencia();
        System.out.println("asdfkhaskjdj");
    }//GEN-LAST:event_jButtonNuevaBombillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTestBombillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTestBombillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTestBombillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTestBombillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTestBombillas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MisComponentes.JBombilla.JBombilla jBombilla1;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonEncender;
    private javax.swing.JButton jButtonNuevaBombilla;
    private javax.swing.JButton jButtonReponer;
    private javax.swing.JComboBox<String> jComboBoxUbicaciones;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JList<String> jListBombillasReponer;
    private javax.swing.JPanel jPanelBombillas;
    private javax.swing.JPanel jPanelUbicaciones;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
