/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import MisComponentes.JBombilla.JBombilla;
import MisComponentes.JBombilla.JBombillaEvent;
import MisComponentes.JBombilla.JBombillaListener;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.border.LineBorder;

/**
 *
 * @author usuario
 */
public class JFrameTestBombillas extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTestBombillas
     */
    public JFrameTestBombillas() {
        initComponents();
        this.setMinimumSize(new Dimension(WIDTH,JBombilla.Ubicaciones.values().length*32+80+250));
        iniciaMisComponenetes();
    }

    /**
     * Inicia los componentes del Frame.
     */
    private void iniciaMisComponenetes() {
        jPanelBombillas.setLayout(new OwnLayoutManager());
        jPanelBombillas.setMaximumSize(new Dimension(255*4,HEIGHT));
        jComboBoxUbicaciones.setModel(new DefaultComboBoxModel(JBombilla.Ubicaciones.values()));
        cargarRadioButtons();
    }

    ButtonGroup bG = new ButtonGroup();
    /**
     * Carga los RadioButtons en la pantalla en funcion de los valores que haya
     * en el tipo enumerado Ubicaciones del componente JBombilla.
     */
    private void cargarRadioButtons() {
        for (JBombilla.Ubicaciones u : JBombilla.Ubicaciones.values()) {
            JRadioButton rBT = new JRadioButton(u.toString());
            rBT.setActionCommand(u.toString());
            rBT.setPreferredSize(new Dimension(200, 30/*(this.getHeight()-173)/Genero.values().length*/));
            rBT.setBorder(new LineBorder(Color.BLACK, 1));
            rBT.setBorderPainted(true);
            jPanelUbicaciones.add(rBT);
            bG.add(rBT);
        }
        consistencia();
    }

    /**
     * Gestiona la consistencia del Frame
     */
    private void consistencia() {
        jListBombillasReponer.setModel(listadoFundidas);
        jPanelBombillas.repaint();
        jPanelUbicaciones.revalidate();
    }
    
    private DefaultListModel listadoFundidas = new DefaultListModel();
    
    /**
     * Listener del componente JBombilla.
     */
    private class gestorBombillas implements JBombillaListener{
        
        @Override
        public void bombillaEncendida(JBombillaEvent evt) {
            System.out.println("********Info Bombilla********");
            System.out.println("Tiempo encendida → "+evt.getSegundosEncendida());
            System.out.println("Numero encendidos → "+evt.getNumeroEncendidos());
        }
        
        @Override
        public void bombillaAgotada(JBombillaEvent evt) {
            listadoFundidas.addElement((JBombilla) evt.getSource());
            consistencia();
        }

        @Override
        public void bombillaRepuesta(JBombillaEvent evt) {
            listadoFundidas.removeElement((JBombilla) evt.getSource());
            consistencia();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBombillas = new javax.swing.JPanel();
        jPanelUbicaciones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonApagar = new javax.swing.JButton();
        jButtonEncender = new javax.swing.JButton();
        jComboBoxUbicaciones = new javax.swing.JComboBox<>();
        jButtonNuevaBombilla = new javax.swing.JButton();
        jLabelUbicacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListBombillasReponer = new javax.swing.JList<>();
        jButtonReponer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBombillas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bombillas"));
        jPanelBombillas.setAutoscrolls(true);
        jPanelBombillas.setLayout(null);

        jPanelUbicaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ubicaciones"));
        jPanelUbicaciones.setLayout(new java.awt.GridLayout(0, 1));

        jButtonApagar.setText("Apagar");
        jButtonApagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarEncenderActionPerformed(evt);
            }
        });

        jButtonEncender.setText("Encender");
        jButtonEncender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarEncenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButtonEncender, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonApagar, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jButtonEncender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelUbicaciones.add(jPanel1);

        jComboBoxUbicaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonNuevaBombilla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonNuevaBombilla.setText("Nueva Bombilla");
        jButtonNuevaBombilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaBombillaActionPerformed(evt);
            }
        });

        jLabelUbicacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUbicacion.setText("Ubicación:");

        jScrollPane1.setViewportView(jListBombillasReponer);

        jButtonReponer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonReponer.setText("REPONER");
        jButtonReponer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReponerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNuevaBombilla, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxUbicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 897, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(jButtonReponer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelBombillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelUbicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBombillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelUbicaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxUbicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevaBombilla)
                    .addComponent(jButtonReponer))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gestion del boton añadir nueva bombilla al panel de bombillas.
     * @param evt 
     */
    private void jButtonNuevaBombillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaBombillaActionPerformed
        JBombilla bombilla=new JBombilla((JBombilla.Ubicaciones) jComboBoxUbicaciones.getSelectedItem());
        bombilla.addJBombillaListener(new gestorBombillas());
        jPanelBombillas.add(bombilla);
        consistencia();
    }//GEN-LAST:event_jButtonNuevaBombillaActionPerformed

    /**
     * Gestion de los botones Apagar y Encender del Frame para gestionar el 
     * encendido apagado de las bombillas de una misma ubicacion.
     * @param evt 
     */
    private void jButtonApagarEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarEncenderActionPerformed
        try{
            for (JBombilla jBM: JBombilla.getColeccionBombillas()){
                if(jBM.getUbicacion().toString().equals(bG.getSelection().getActionCommand()))
                    if((JButton)evt.getSource()==jButtonApagar)jBM.apagar();
                    else jBM.encender();
            }
        }catch(Exception e){}
    }//GEN-LAST:event_jButtonApagarEncenderActionPerformed

    /**
     * Gestion del boton reponer, actua solo sobre los componentes seleccionados 
     * en el Jlist
     * @param evt 
     */
    private void jButtonReponerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReponerActionPerformed
        if(jListBombillasReponer.getSelectedIndex()==-1)return;
        for( Object o : jListBombillasReponer.getSelectedValues()){
            ((JBombilla) o).reponer();
//            listadoFundidas.removeElement((JBombilla) evt.getSource());
        }
        consistencia();
    }//GEN-LAST:event_jButtonReponerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameTestBombillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameTestBombillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameTestBombillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameTestBombillas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameTestBombillas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonEncender;
    private javax.swing.JButton jButtonNuevaBombilla;
    private javax.swing.JButton jButtonReponer;
    private javax.swing.JComboBox<String> jComboBoxUbicaciones;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JList<String> jListBombillasReponer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBombillas;
    private javax.swing.JPanel jPanelUbicaciones;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
