package primero;
// Generated 05-feb-2018 11:48:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Auxdept generated by hbm2java
 */
public class Auxdept  implements java.io.Serializable {


     private byte deptNo;
     private String dnombre;
     private String loc;
     private Set auxempls = new HashSet(0);

    public Auxdept() {
    }

	
    public Auxdept(byte deptNo) {
        this.deptNo = deptNo;
    }
    public Auxdept(byte deptNo, String dnombre, String loc, Set auxempls) {
       this.deptNo = deptNo;
       this.dnombre = dnombre;
       this.loc = loc;
       this.auxempls = auxempls;
    }
   
    public byte getDeptNo() {
        return this.deptNo;
    }
    
    public void setDeptNo(byte deptNo) {
        this.deptNo = deptNo;
    }
    public String getDnombre() {
        return this.dnombre;
    }
    
    public void setDnombre(String dnombre) {
        this.dnombre = dnombre;
    }
    public String getLoc() {
        return this.loc;
    }
    
    public void setLoc(String loc) {
        this.loc = loc;
    }
    public Set getAuxempls() {
        return this.auxempls;
    }
    
    public void setAuxempls(Set auxempls) {
        this.auxempls = auxempls;
    }




}


