package primero;
// Generated 24-ene-2018 13:39:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Auxempl  implements java.io.Serializable {


     private short empNo;
     private Auxdept departamentos;
     private String apellido;
     private String oficio;
     private Integer dir;
     private Date fechaAlta;
     private Float salario;
     private Float comision;

    public Auxempl() {
    }

	
    public Auxempl(short empNo) {
        this.empNo = empNo;
    }
    public Auxempl(short empNo, Auxdept departamentos, String apellido, String oficio, Integer dir, Date fechaAlta, Float salario, Float comision) {
       this.empNo = empNo;
       this.departamentos = departamentos;
       this.apellido = apellido;
       this.oficio = oficio;
       this.dir = dir;
       this.fechaAlta = fechaAlta;
       this.salario = salario;
       this.comision = comision;
    }
   
    public short getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(short empNo) {
        this.empNo = empNo;
    }
    public Auxdept getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Auxdept departamentos) {
        this.departamentos = departamentos;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getOficio() {
        return this.oficio;
    }
    
    public void setOficio(String oficio) {
        this.oficio = oficio;
    }
    public Integer getDir() {
        return this.dir;
    }
    
    public void setDir(Integer dir) {
        this.dir = dir;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Float getSalario() {
        return this.salario;
    }
    
    public void setSalario(Float salario) {
        this.salario = salario;
    }
    public Float getComision() {
        return this.comision;
    }
    
    public void setComision(Float comision) {
        this.comision = comision;
    }

     @Override
    public String toString(){
        return String.format("%-4d%-30s%-10s%-3d%-15s%-10.2f%-10.2f", this.empNo,this.apellido,this.oficio,this.dir,this.fechaAlta.toString(),this.salario,this.comision);
    }

}


