/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejemplos;

import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.SwingConstants;

/**
 *
 * @author usuario
 */
public class Ejemplo2GroupLayout extends javax.swing.JFrame {

    /**
     * Creates new form Ejemplo2GroupLayout
     */
    public Ejemplo2GroupLayout() {
        initComponents();
        initLayoutDinamico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelDinamico = new javax.swing.JPanel();
        jPanelEstatico = new javax.swing.JPanel();
        jRadioButtonJProyecto = new javax.swing.JRadioButton();
        jRadioButtonTHoras = new javax.swing.JRadioButton();
        jRadioButtonTMontador = new javax.swing.JRadioButton();
        jRadioButtonTComision = new javax.swing.JRadioButton();
        jButtonAñadir = new javax.swing.JButton();
        jButtonBorrarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDinamico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tipo Trabajador"));
        jPanelDinamico.setLayout(null);

        jPanelEstatico.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tipo Trabajador"));

        buttonGroup1.add(jRadioButtonJProyecto);
        jRadioButtonJProyecto.setText("Jefe Proyecto");

        buttonGroup1.add(jRadioButtonTHoras);
        jRadioButtonTHoras.setText("Trabajador por horas");

        buttonGroup1.add(jRadioButtonTMontador);
        jRadioButtonTMontador.setText("Trabajador montador");

        buttonGroup1.add(jRadioButtonTComision);
        jRadioButtonTComision.setText("Trabajador a comision");

        jButtonAñadir.setText("Añadir");

        jButtonBorrarDatos.setText("Borrar Datos");

        javax.swing.GroupLayout jPanelEstaticoLayout = new javax.swing.GroupLayout(jPanelEstatico);
        jPanelEstatico.setLayout(jPanelEstaticoLayout);
        jPanelEstaticoLayout.setHorizontalGroup(
            jPanelEstaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstaticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButtonBorrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(jPanelEstaticoLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanelEstaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonJProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jRadioButtonTMontador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonTComision, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jRadioButtonTHoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEstaticoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAñadir, jButtonBorrarDatos});

        jPanelEstaticoLayout.setVerticalGroup(
            jPanelEstaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstaticoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jRadioButtonJProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonTHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonTMontador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonTComision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelEstaticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAñadir)
                    .addComponent(jButtonBorrarDatos)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelEstatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelEstatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplo2GroupLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplo2GroupLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplo2GroupLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplo2GroupLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo2GroupLayout().setVisible(true);
            }
        });
    }
    
    private void initLayoutDinamico(){
        buttonGroup=new ButtonGroup();
        jButtonAñadir1=new JButton("Añadir");
        jButtonBorrarDatos1=new JButton("Borrar Datos");
        jRadioButtonJProyecto1= new JRadioButton("Jefe Proyecto");
        buttonGroup.add(jRadioButtonJProyecto1);
        jRadioButtonTComision1= new JRadioButton("Tabajdor Comision");
        buttonGroup.add(jRadioButtonTComision1);
        jRadioButtonTHoras1= new JRadioButton("Trabajador Horas");
        buttonGroup.add(jRadioButtonTHoras1);
        jRadioButtonTMontador1= new JRadioButton("Trabajador Montador");
        buttonGroup.add(jRadioButtonTMontador1);
        
        
        GroupLayout layoutCopia= new GroupLayout(jPanelDinamico);
        jPanelDinamico.setLayout(layoutCopia);
        layoutCopia.setAutoCreateContainerGaps(true);
        layoutCopia.setAutoCreateGaps(true);
        
        layoutCopia.setHorizontalGroup(layoutCopia.createParallelGroup()
            .addGroup(layoutCopia.createSequentialGroup()
                .addGap(0,0,1000)
                .addGroup(layoutCopia.createParallelGroup()
                .addComponent(jRadioButtonJProyecto1)
                .addComponent(jRadioButtonTComision1)
                .addComponent(jRadioButtonTMontador1)
                .addComponent(jRadioButtonTHoras1)
                )
                .addGap(0,0,1000)
            )
                    
            .addGroup(layoutCopia.createSequentialGroup()
                .addComponent(jButtonAñadir1)
                .addGap(0,0,1000)
                .addComponent(jButtonBorrarDatos1)
            )
        );
        
        layoutCopia.linkSize(SwingConstants.HORIZONTAL, jRadioButtonJProyecto1,jRadioButtonTComision1,jRadioButtonTHoras1,jRadioButtonTMontador1);
        layoutCopia.linkSize(SwingConstants.HORIZONTAL, jButtonBorrarDatos1,jButtonAñadir1);
        
        layoutCopia.setVerticalGroup(layoutCopia.createSequentialGroup()
            
            .addGroup(layoutCopia.createParallelGroup()
                .addComponent(jRadioButtonJProyecto1,-1,-1,1000)
                .addComponent(jRadioButtonTComision1,-1,-1,1000)
                .addComponent(jRadioButtonTMontador1,-1,-1,1000)
                .addComponent(jRadioButtonTHoras1,-1,-1,1000)
            )
            .addGroup(layoutCopia.createParallelGroup()
                .addComponent(jButtonAñadir1)
                .addComponent(jButtonBorrarDatos1)
            )
        );
        
        
        //TODO VERTICAL GROUP
    }
    
    //<editor-fold defaultstate="collapsed" desc="miscomponentes">
    
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonAñadir1;
    private javax.swing.JButton jButtonBorrarDatos1;
    private javax.swing.JRadioButton jRadioButtonJProyecto1;
    private javax.swing.JRadioButton jRadioButtonTComision1;
    private javax.swing.JRadioButton jRadioButtonTHoras1;
    private javax.swing.JRadioButton jRadioButtonTMontador1;
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonBorrarDatos;
    private javax.swing.JPanel jPanelDinamico;
    private javax.swing.JPanel jPanelEstatico;
    private javax.swing.JRadioButton jRadioButtonJProyecto;
    private javax.swing.JRadioButton jRadioButtonTComision;
    private javax.swing.JRadioButton jRadioButtonTHoras;
    private javax.swing.JRadioButton jRadioButtonTMontador;
    // End of variables declaration//GEN-END:variables
}
