/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejemplos;

import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author usuario
 */
public class Ejemplo1GroupLayou extends javax.swing.JFrame {

    /**
     * Creates new form Ejemplo1GroupLayou
     */
    public Ejemplo1GroupLayou() {
        initComponents();
        initLayoutDinamico();
    }
    private void initLayoutDinamico(){
        jTextFieldPrimerDato1= new JTextField();
        jTextFieldSegundoDato1= new JTextField();
        jTextFieldTercerDato1= new JTextField();
        jLabelPrimerDato1 = new JLabel("primer Dato");
        jLabelSegundoDato1 = new JLabel("Segundo Dato");
        jLabelTercerDato1 = new JLabel("Tercer Dato");
        jLabelPrimerDato1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSegundoDato1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTercerDato1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        
        GroupLayout layoutCopia= new GroupLayout(jPanelDatosDinamicos);
        jPanelDatosDinamicos.setLayout(layoutCopia);
        layoutCopia.setAutoCreateContainerGaps(true);
        layoutCopia.setAutoCreateGaps(true);
        
        layoutCopia.setHorizontalGroup(layoutCopia.createSequentialGroup()
            .addGroup(layoutCopia.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addComponent(jLabelPrimerDato1,GroupLayout.Alignment.TRAILING,-1,-1,100)
                .addComponent(jLabelSegundoDato1,GroupLayout.Alignment.TRAILING,-1,-1,100)
                .addComponent(jLabelTercerDato1,GroupLayout.Alignment.TRAILING,-1,-1,100)
            )
            .addGroup(layoutCopia.createParallelGroup()
                .addComponent(jTextFieldPrimerDato1,-2,150,-2)
                .addComponent(jTextFieldSegundoDato1,-2,150,-2)
                .addComponent(jTextFieldTercerDato1,-2,150,-2)
            )
            .addContainerGap(45,Short.MAX_VALUE)
        );
        
        layoutCopia.linkSize(SwingConstants.HORIZONTAL,jLabelPrimerDato1,jLabelSegundoDato1,jLabelTercerDato1);
        
        layoutCopia.setVerticalGroup(layoutCopia.createSequentialGroup()
            .addGroup(layoutCopia.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelPrimerDato1)
                .addComponent(jTextFieldPrimerDato1)
            )
            .addGroup(layoutCopia.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelSegundoDato1)
                .addComponent(jTextFieldSegundoDato1)
            )
            .addGroup(layoutCopia.createParallelGroup(GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelTercerDato1)
                .addComponent(jTextFieldTercerDato1)
            )
        );
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatos = new javax.swing.JPanel();
        jLabelPrimerDato = new javax.swing.JLabel();
        jLabelSegundoDato = new javax.swing.JLabel();
        jLabelTercerDato = new javax.swing.JLabel();
        jTextFieldSegundoDato = new javax.swing.JTextField();
        jTextFieldPrimerDato = new javax.swing.JTextField();
        jTextFieldTercerDato = new javax.swing.JTextField();
        jPanelDatosDinamicos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos"));

        jLabelPrimerDato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrimerDato.setText("Primer dato");

        jLabelSegundoDato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelSegundoDato.setText("Segundo Dato");

        jLabelTercerDato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTercerDato.setText("Tercer Dato");

        jTextFieldSegundoDato.setText("jTextField1");

        jTextFieldPrimerDato.setText("jTextField1");

        jTextFieldTercerDato.setText("jTextField1");

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTercerDato, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelPrimerDato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSegundoDato, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelDatosLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldSegundoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldPrimerDato, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTercerDato, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelPrimerDato, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldPrimerDato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelSegundoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldSegundoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelTercerDato, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldTercerDato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelDatosDinamicos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Dinamico"));
        jPanelDatosDinamicos.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosDinamicos, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatosDinamicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplo1GroupLayou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplo1GroupLayou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplo1GroupLayou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplo1GroupLayou.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo1GroupLayou().setVisible(true);
            }
        });
    }
   //<editor-fold defaultstate="collapsed" desc="Componentes dinamicos">
    private javax.swing.JLabel jLabelPrimerDato1;
    private javax.swing.JLabel jLabelSegundoDato1;
    private javax.swing.JLabel jLabelTercerDato1;
    private javax.swing.JTextField jTextFieldPrimerDato1;
    private javax.swing.JTextField jTextFieldSegundoDato1;
    private javax.swing.JTextField jTextFieldTercerDato1;
//</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPrimerDato;
    private javax.swing.JLabel jLabelSegundoDato;
    private javax.swing.JLabel jLabelTercerDato;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelDatosDinamicos;
    private javax.swing.JTextField jTextFieldPrimerDato;
    private javax.swing.JTextField jTextFieldSegundoDato;
    private javax.swing.JTextField jTextFieldTercerDato;
    // End of variables declaration//GEN-END:variables
}
